README.md

Hope it helps someone else. :)

Update readme.md with the feathers + next.js example

---

README.md

Add telegram chat link

---

README.md

add russian article

---

README.md

Add featherjs-couchbase to the list of packages

Add feathersjs-couchbase

---

README.md

@feathersjs/authentication-local link fix

authentication-local link fix

---

README.md

This is the article https://weburoki.pro/querying-feathersjs-service

Add Russian article abour querying

---

README.md

Add [MyEthereum.app repo](https://github.com/petermikitsh/myethereumapp) to example list. This example is a solid basis for a production application -- it combines Feathers, Sequelize, React, Redux, Next.js, and Jest. It also has hot-module reloading for both the client and server.

Add MyEthereum.app example

---

README.md

This module contains a set of Express middleware and FeathersJS hooks to automate distributed tracing for FeathersJS services using OpenTracing and your preferred Tracer (e.g. Jaeger).

Added feathers-opentracing

---

README.md

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).
Thanks for contributing …

Add feathers-arangodb to databases

---

README.md

Added my implementation of feathers with both Vue.js or Nuxt.js

Add feathers-vue-nuxt to examples

---

README.md

[feathers-cassandra](https://github.com/dekelev/feathers-cassandra)

Added feathers-cassandra

---

README.md

A Feathers + Nuxt Boilerplate, with Sign up, Login, Reauthentication, and a few other things. Documentation exists.
If your changes involve documentation updates please mention that …

Feathers + Nuxt Boilerplate

---

README.md

Added wings-feathers (Framework Agnostic) and FeathersQuery (Utilities) as New Tools
If your changes involve documentation updates please mention that and link the appropriate PR in …

wings-feathers and FeathersQuery as New Tools

---

README.md

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).
Thanks for contributing …

Add feathers-nuxt sao template to list

---

README.md

Added the module feathers-splunk into the awesome-feathersjs.

Added module of Feathers-splunk.

---

README.md

add example of feathers chat and login with facebook

Add example of chat plus login with facebook

---

README.md

Add phone signup and sms verify example.

Add example of signing up via phone and sms pin

---

README.md

[feathers-kong](https://github.com/dekelev/feathers-kong) - A Feathers service for [Kong API Gateway](https://docs.konghq.com) admin API
Manage Kong resources (i.e. `Consumer`, `Jwt`) with Feathers services (i.e. `kong/consumers`, `kong/jwts`)

Added feathers-kong

---

README.md

Link to [Frontless](https://github.com/nesterow/frontless). Frontless uses feathersjs client in browser and on the server side
If your changes involve documentation updates please …

Feathers + RiotJS isomorphic application

---

README.md

One line change to add a new project to "Projects Using Feathers."
If your changes involve documentation updates please mention that and link the appropriate PR in …

Added a "Projects Using Feathers"

---

README.md

[feathers-aws-sns](https://github.com/powerkernel/feathers-aws-sns) - Feathers AWS SNS service to use with Amazon Simple Notification Service (service)

Add feathers aws sns

---

README.md

Handle HubSpot webhooks in a FeathersJS service

Added feathers-hubspot-webhooks

---

README.md

Add google-like $search to NeDB service.find queries.
If your changes involve documentation updates please mention that and link the appropriate PR in …

google-like $search under Database

---

README.md

* Alphabetize database adapters
* Add feathers-bee-queue

Update list of database service adapters

---

README.md

adding new feathers v4 client app built with aurelia

aurelia-feathers-fusebox with i18next

---

README.md

Thanks for the great work on Feathers!
I added a TypeScript version of the Feathers Chat React example from my repository.
And requested by no one, but I thought it would be helpful to organize the list of examples as it's pretty long now. If this an unwanted change, but you would like to include the TS React example, I can submit another PR with just it added to the list.

added react+typescript chat example & reorganized the examples

---

README.md

This PR updates the `feathers-hooks-common` docs URL. It also adds a new link for `feathers-fletching`.

Update `feathers-hooks-common` docs url, add `feathers-fletching`

---

README.md

- Added feathers-coinapi
- Added feathers-algolia
- Added feathers-cloudinary
- Added Cryptosheets to 'Projects using Feathers'

added cloudinary, coinapi, and algolia

---

README.md

Adding:
[feathers-lowdb](https://github.com/lwhiteley/feathers-lowdb) - Featherjs database service adapter for [Lowdb][https://github.com/typicode/lowdb]

chore: add feathers-lowdb to database adapter list

---

README.md

small edit to format link
related to #51

chore: fix markdown link for lowdb

---

README.md

Adding to Utilities:
[feathers-async-bootstrap](https://github.com/idaho/feathers-async-boot) - Booting feathers application asynchron

add 'feathers-async-boot' to utilities list

---

README.md

It is a simple transport that exposes a way to communicate with the methods of the services by using a RabbitMQ message broker to have async communication with other services/workers.
I have been using this simple implementation in my projects and I only wanted to give my little contribution to this awesome framework.

Add external RabbitMQ Transport to README.

---

README.md

- Add [@feathers-weapp/client](https://github.com/xixilive/feathers-client-weapp) -  feathers rest client for wechat mini-program
- Add [@feathers-weapp/auth](https://github.com/xixilive/feathers-authentication-weapp) -  feathers auth strategy for wechat mini-program

add Awesome Feathers for wechat

---

README.md

Just adding some links to some projects related to feathers. Thank you!
- feathers-airtable is a a common API adapter for Airtable
- ccsunlight.org is a civic engagement project that uses feathers.

Adding feathers-airtable and ccsunlight.org links

---

README.md

Hey. In my spare time I want to introduce my package that I am working on. A small package that I developed with react for react. Currently, functions for auth operations and crud operations are available. You can visit https://github.com/indatawetrust/use-feathers for codes and https://naughty-cray-bdab6d.netlify.app/ for demo. Thank you.

use-feathers package added

---

README.md

- feathers-postmark
- feathers-shallow-populate
- feathers-graph-populate

add postmark, shallow-populate & graph-populate

---

README.md

Distribute FeathersJS apps over the network with inter-service communication using HTTP protocol.
https://github.com/dekelev/feathers-http-distributed

Added the feathers-http-distributed module

---

README.md

Added a link for a project template for Feathers-React: Equipped with Redux Toolkit and Ant Design.

Add new resource for React

---

README.md

Added [feathers-authentication-oidc](https://www.npmjs.com/package/feathers-authentication-oidc)

Added feathers-authentication-oidc

---

README.md

Add FlutterFeathersjs, a flutter client to communicate with your feathers js server from google flutter app.
__Communicate with your feathers js server from flutter__
This is not really an issue but a request to add a flutter plugin which i'm developping and maintained.
- Authentication et reAuthentication trougth rest and socketio 
- File upload is supported on rest client
- All rest methods are implemented
- All socketio methods are implemented
- Socketio event listen method are implemented
- Example app is coming
For more infos:
See it on github: https://github.com/Dahkenangnon/flutter_feathersjs.dart
See it on Pub.dev:  https://pub.dev/packages/flutter_feathersjs/
I :heart: Feathers 🐦

Add FlutterFeathersjs, a flutter client.

---

README.md

Added references to FeathersJS Offline-first.

Added references to @feathersjs-offline

---

README.md

feathers-casl: fix typo

---

README.md

I've published a small wrapper for https://openweathermap.org/api.

add feathers-openweathermap

---

README.md

I've published a new feathers database adapter for ottoman

add feathers-ottoman

---

README.md

Added reference to `@feathersjs-offline` and removed double entry.

Added reference to @feathersjs-offline

---

README.md

add [feathers-trigger](https://github.com/fratzinger/feathers-trigger) to section **hooks**.

add feathers-trigger

---

README.md

Adding a project that uses Feathers: Adaptable.io.
Adaptable not only uses Feathers internally, but also makes it easy to deploy Feathers apps, complete with database, HTTPS, etc.

Add Adaptable.io

---

README.md

Add XREngine (400 stars on Github, 18,000 commits, uses Feathers 5 extensively)
Move Juno from bottom into alphabetical order

Update "Projects Using Feathers"
